metadata_directory: metadata
services:
  mailhog:
    port: 8025
  hasura:
    version: v2.2.0
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
  auth:
    version: 0.7.1
auth:
  log_level: debug
  access_control:
    email:
      allowed_email_domains: ''
      allowed_emails: ''
      blocked_email_domains: ''
      blocked_emails: ''
    allowed_redirect_urls: ''
  anonymous_users:
    enabled: false
  client_url: http://localhost:3000
  disable_new_users: false
  email:
    passwordless:
      enabled: true
    template:
      fetch_url: ''
    signin_email_verified_required: true
  gravatar:
    default: ''
    enabled: true
    rating: ''
  locale:
    allowed_locales: en,fr
    default: en
  password:
    hibp:
      enabled: false
    min_length: 3
  provider:
    apple:
      client_id: ''
      enabled: false
      key_id: ''
      private_key: ''
      scope: name,email
      team_id: ''
    bitbucket:
      client_id: ''
      client_secret: ''
      enabled: false
    facebook:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: email,photos,displayName
    github:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: user:email
      token_url: ''
      user_profile_url: ''
    gitlab:
      base_url: ''
      client_id: ''
      client_secret: ''
      enabled: false
      scope: read_user
    google:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: email,profile
    linkedin:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: r_emailaddress,r_liteprofile
    spotify:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: user-read-email,user-read-private
    strava:
      client_id: ''
      client_secret: ''
      enabled: false
    twilio:
      account_sid: ''
      auth_token: ''
      enabled: false
      messaging_service_id: ''
    twitter:
      consumer_key: ''
      consumer_secret: ''
      enabled: false
    windows_live:
      client_id: ''
      client_secret: ''
      enabled: false
      scope: wl.basic,wl.emails,wl.contacts_emails
  sms:
    passwordless:
      enabled: true
    provider: twilio
    twilio:
      account_sid: ''
      auth_token: ''
      messaging_service_id: ''
  smtp:
    host: nhost_mailhog
    auth_method: ''
    pass: password
    port: 1807
    secure: false
    sender: hasura-auth@example.com
    user: user
  access_token:
    expires_in: 900
  refresh_token:
    expires_in: 43200
  user:
    default_allowed_roles: user,me
    default_role: user
  mfa:
    enabled: false
    totp_issuer: nhost

storage: {}

version: 3
